site_name: Tome Documentation
site_url: https://sitename.example
theme:
  name: material
  features:
    - navigation.footer
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/roblox
      link: https://www.roblox.com/users/5104349571/profile
    - icon: simple/github
      link: https://github.com/y29r
    - icon: simple/discord
      link: https://discord.com/users/1160614251090690068
    - icon: simple/x
      link: https://x.com/real_y29r

copyright: Copyright &copy; 2024 bytenand
